PUT oci
{
  "mappings": {
    "properties": {
      "data": {
        "message": {"type": "text"},
        "tailed_path": {"type": "text"}
      },
      "id": {"type": "text"},
      "oracle": {
        "compartmentid": {"type": "text"},
        "ingestedtime": {"type": "text"},
        "instanceid": {"type": "text"},
        "loggroupid": {"type": "text"},
        "logid": {"type": "text"},
        "tenantid": {"type": "text"}
      },
      "source": {"type": "text"},
      "specversion": {"type": "text"},
      "subject": {"type": "text"},
      "time": {"type": "text"},
      "type": {"type": "text"}
    }
  }
}