@endpoint = <deployment-endpoint>

POST {{endpoint}}/messages HTTP/1.1
Content-Type: application/json

[
    {
        "tag": "test.test",
        "created": "2023-07-06T01:25:22Z",
        "body": "{ \"first\": 1, \"second\": 2, \"text\": \"this is test message.\" }"
    },
    {
        "tag": "test.test",
        "created": "2023-07-06T01:25:22Z",
        "body": "{ \"first\": 1, \"second\": 2, \"text\": \"this is test message.\" }"
    }
]
