name: OCI Service Connector Hub Streaming JSON to CSV

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"
          cache: maven

      - name: Format chack
        working-directory: oci-sch-streaming-json-to-csv
        run: |
          mvn formatter:validate

      - name: Test with Maven
        working-directory: oci-sch-streaming-json-to-csv
        run: |
          mvn test
